# **Numpy

**most commonly used for data analysis**\
**written forscitenfic computing data analysis**

In [4]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
print()

In [5]:
import numpy as np
a=np.array(a)
b=np.array(b)
a+b

array([ 7,  9, 11, 13, 15])

In [6]:
a=[i for i in range(1,101)]
b=[i for i in range(1,101)]
%timeit c=[i+j for i,j in zip(a,b)]
a=np.array(a)
b=np.array(b)
%timeit a+b

17.2 µs ± 417 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.24 µs ± 5.95 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy

In [9]:
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
import numpy as np
a=np.array([1,2,3,4,5,])
print(a)

[1 2 3 4 5]


In [11]:
a=np.array((1,2,3,4,5))
print(a)

[1 2 3 4 5]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[0])

1


In [14]:
a=np.array({1,2,3,4,5})
print(a)

{1, 2, 3, 4, 5}


In [20]:
a={1,2,3,4,5}
print(a)

{1, 2, 3, 4, 5}


In [21]:
a= np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [26]:
range(1,100,2)

range(1, 100, 2)

In [27]:
a=np.arange(1,10,0.5)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [28]:
print(a[0])

1.0


In [29]:
a = np.linspace(1,100,12)
print(a)

[  1.  10.  19.  28.  37.  46.  55.  64.  73.  82.  91. 100.]


In [30]:
a=np.linspace(100,200,12)
print(a)

[100.         109.09090909 118.18181818 127.27272727 136.36363636
 145.45454545 154.54545455 163.63636364 172.72727273 181.81818182
 190.90909091 200.        ]


In [31]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [32]:
a=np.ones((5,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
a=np.ones((3,2,2))
print(a)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [34]:
a=np.array([1,2,3,4,5])
np.ones_like(a)

array([1, 1, 1, 1, 1])

In [35]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [36]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
a = np.full(5,7)
print(a)

[7 7 7 7 7]


In [38]:
a = np.full((2,3),6)
print(a)

[[6 6 6]
 [6 6 6]]


In [39]:
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [40]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim)
print(a)

2
[[1 2 3 4]
 [5 6 7 8]]


In [41]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [42]:
a=np.array([1,2,3,4,5])
print(a.dtype)

int32


In [43]:
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [44]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
a=np.arange(14).reshape(1,-1)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]]


In [49]:
a.ndim

2

In [50]:
a=np.arange(12).reshape(-1,1)
print(a)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [51]:
a=np.array([1,2,3,4,5],dtype='int16')
print(a)

[1 2 3 4 5]


In [52]:
a[0]

1

In [53]:
len(a)

5

In [54]:
a[1]

2

In [59]:
a.index

AttributeError: 'numpy.ndarray' object has no attribute 'index'

**indexing**

In [60]:
a[1:4]

array([2, 3, 4], dtype=int16)

In [61]:
a[2:5]

array([3, 4, 5], dtype=int16)

In [62]:
a[-1:]

array([5], dtype=int16)

In [63]:
a[-1]

5

In [64]:
a[-3]

3

In [65]:
a[::-1]

array([5, 4, 3, 2, 1], dtype=int16)

In [66]:
a

array([1, 2, 3, 4, 5], dtype=int16)

In [67]:
a=np.arange(12).reshape(3,-1)
print(a.shape)
print(a)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [68]:
a[2,1]

9

In [69]:
a[1,1:3]

array([5, 6])

In [70]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [71]:
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [72]:
a[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
a[0,0,0]

0

In [74]:
a[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
a[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [79]:
a[1,1,1]

9

In [80]:
a[0:,1:3,0:2]

array([[[ 2,  3],
        [ 4,  5]],

       [[ 8,  9],
        [10, 11]]])

# sorting

In [81]:
a=np.array([4,3,1,5,2,7])
np.sort(a)

array([1, 2, 3, 4, 5, 7])

In [82]:
a=np.arange(12,0,-1).reshape(3,4)
np.sort(a)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [83]:
a=np.arange(12,0,-1).reshape(3,4)
print(a)
np.sort(a,axis=0)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [84]:
places = ['vjw','ong','gnt']
dist = ['krishna','prakasam','guntur']
a = np.lexsort((places,dist))
print(a)

[2 0 1]


In [85]:
[places[i]+''+dist[i]for i in a]

['gntguntur', 'vjwkrishna', 'ongprakasam']

# math

In [86]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a,b)

[1 2 3 4 5] [ 6  7  8  9 10]


In [87]:
a+b

array([ 7,  9, 11, 13, 15])

In [88]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [89]:
a//b

array([0, 0, 0, 0, 0], dtype=int32)

In [90]:
b//a

array([6, 3, 2, 2, 2], dtype=int32)

In [91]:
b/a

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [92]:
a*b

array([ 6, 14, 24, 36, 50])

In [93]:
a%b

array([1, 2, 3, 4, 5], dtype=int32)

In [94]:
b%a

array([0, 1, 2, 1, 0], dtype=int32)

In [95]:
np.divide(a,b)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [96]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [97]:
np.divmod(a,b)

(array([0, 0, 0, 0, 0], dtype=int32), array([1, 2, 3, 4, 5], dtype=int32))

In [98]:
np.divmod(b,a)

(array([6, 3, 2, 2, 2], dtype=int32), array([0, 1, 2, 1, 0], dtype=int32))

In [99]:
print(b,a)

[ 6  7  8  9 10] [1 2 3 4 5]


In [100]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [101]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [102]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])